base: /
baseVariants:
  -
    base: 'https://mycountry-portal.ddev.site/'
    condition: 'applicationContext == "Production"'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=2'
flux_content_types: ''
flux_page_templates: ''
languages:
  -
    title: ''
    enabled: true
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: global
    languageId: 0
rootPageId: 1
websiteTitle: 'Country Portal'
